name: p2panda
description: p2panda FFI bindings for Dart
version: 0.1.0
repository: https://github.com/p2panda/meli
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: 2.1.2
  flutter_rust_bridge: 1.82.6
  freezed_annotation: 2.4.1
  meta: 1.12.0
  uuid: 4.4.0

dev_dependencies:
  build_runner: 2.4.6
  ffigen: 8.0.2
  freezed: 2.4.1
