name: p2panda
description: p2panda FFI bindings for Dart
version: 0.1.0
repository: https://github.com/p2panda/meli
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.82.1
  freezed_annotation: ^2.2.0
  meta: ^1.8.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  ffigen: ^8.0.2
  freezed: ^2.4.0
  test: ^1.21.0
